AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Todo Service 

Metadata:
  AWS::ServerlessRepo::Application:
    Name: serverless-todo
    Description: Serverless Todo Service
    Author: mrFlick72
    SpdxLicenseId: Apache-2.0
    Labels: ['playground']
    SemanticVersion: 0.0.1

Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  TodoStorage:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Todo
  DeleteTodo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: TodoStorage
          Permissions:
            - Write
    Properties:
      CodeUri: app/delete-todo
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todo/{id}
            Method: delete
  ReadTodo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: TodoStorage
          Permissions:
            - Read
    Properties:
      CodeUri: app/get-todos
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todo
            Method: get
  SaveTodo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      MyConn:
        Properties:
          Destination:
            Id: TodoStorage
          Permissions:
            - Write
    Properties:
      CodeUri: app/save-todo
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todo
            Method: put